import { Providers } from './providers';

export const metadata = {
  title: 'Sieu toc website',
  description: 'Generated by Sieu toc website',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
