import type { ReactNode } from '@/types';
import { Providers } from './providers';

export const metadata = {
  title: 'Sieutoc Website',
  description: 'Generated by Sieutoc Platform',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
