import type { ReactNode, Locale } from '@/types';
import { Providers } from '@/components/client';

export const metadata = {
  title: 'Sieutoc Website',
  description: 'Generated by Sieutoc Platform',
};

// Cause trouble with server actions
// Read more: https://github.com/vercel/next.js/issues/54992
// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ locale }));
// }

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={params.locale}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
