import type { ReactNode } from '@/types';

import { Locale, i18n } from '@/configs/i18n.config';
import { Providers } from './providers';

export const metadata = {
  title: 'Sieutoc Website',
  description: 'Generated by Sieutoc Platform',
};
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={params.locale}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
