import type { ReactNode } from '@/types';

import { Locale, i18n } from '@/configs/i18n.config';
import { Providers } from './providers';
import { getSession } from 'next-auth/react';

export const metadata = {
  title: 'Sieutoc Website',
  description: 'Generated by Sieutoc Platform',
};
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  const session = await getSession();
  return (
    <html lang={params.locale}>
      <body>
        <Providers session={session} locale={params.locale}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
