name: Code Checking

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code-checking:
    name: Lint, Type check and Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Checking TypeScript
        run: npm run typecheck
